[package]
name = "cool-snake"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
crossterm = "0.29"
ratatui = "0.30"
rand = "0.9"
clap = { version = "4", features = ["derive"] }

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
